Repository Automattic/Gravatar-Android, pull requests merged in 2025-08, with the labels that each got.

#86 [Tooling] Add initial release lane setup
  .buildkite/commands/release-build.sh
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  .buildkite/release-pipelines/new-alpha-release.yml
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
  version.properties
Labels: tooling

#105 [Tooling] Add automation lane to fetch translations
  app/lint.xml
  fastlane/Fastfile
  homeUi/src/main/res/values-ar/strings.xml
  homeUi/src/main/res/values-de/strings.xml
  homeUi/src/main/res/values-es/strings.xml
  homeUi/src/main/res/values-fr/strings.xml
  homeUi/src/main/res/values-in/strings.xml
  homeUi/src/main/res/values-it/strings.xml
  homeUi/src/main/res/values-iw/strings.xml
  homeUi/src/main/res/values-ja/strings.xml
  homeUi/src/main/res/values-ko/strings.xml
  homeUi/src/main/res/values-nl/strings.xml
  homeUi/src/main/res/values-pt-rBR/strings.xml
  homeUi/src/main/res/values-ru/strings.xml
  homeUi/src/main/res/values-sv/strings.xml
  homeUi/src/main/res/values-tr/strings.xml
  homeUi/src/main/res/values-zh-rCN/strings.xml
  homeUi/src/main/res/values-zh-rTW/strings.xml
  homeUi/src/main/res/values/available_languages.xml
  loginUi/src/main/res/values-ar/strings.xml
  loginUi/src/main/res/values-de/strings.xml
  loginUi/src/main/res/values-es/strings.xml
  loginUi/src/main/res/values-fr/strings.xml
  loginUi/src/main/res/values-in/strings.xml
  loginUi/src/main/res/values-it/strings.xml
  loginUi/src/main/res/values-iw/strings.xml
  loginUi/src/main/res/values-ja/strings.xml
  loginUi/src/main/res/values-ko/strings.xml
  loginUi/src/main/res/values-nl/strings.xml
  loginUi/src/main/res/values-pt-rBR/strings.xml
  loginUi/src/main/res/values-ru/strings.xml
  loginUi/src/main/res/values-sv/strings.xml
  loginUi/src/main/res/values-tr/strings.xml
  loginUi/src/main/res/values-zh-rCN/strings.xml
  loginUi/src/main/res/values-zh-rTW/strings.xml
  loginUi/src/main/res/values/available_languages.xml
Labels: tooling

#107 Fix issues in the release build related to Navigation Component
  app/src/main/java/com/gravatar/app/navigation/RootNavigation.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/navigation/HomeNavigation.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/HomeScreen.kt
Labels: bug

#108 Fix avatar scaling issue when expanding the header in the Avatar tab
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.components.GravatarHeaderTest.gravatarHeaderFullyExpanded.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.components.GravatarHeaderTest.gravatarHeaderPartiallyExpanded.png
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/components/AsyncImageWithCachePlaceholder.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/components/GravatarAvatarWithShadow.kt
Labels: bug

#113 Rename tab: Share -> QR
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.HomeScreenTest.homeScreen.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.HomeScreenTest.homeScreenNoInternet.png
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/navigation/HomeNavigation.kt
  homeUi/src/main/res/values/strings.xml
Labels: enhancement

#114 Privacy Settings
  crashlogging/src/main/java/com/gravatar/crashlogging/GravatarCrashLoggingDataProvider.kt
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.components.privacySetting.PrivacySettingsBottomSheetTest.privacySettingsAllDisabled.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.components.privacySetting.PrivacySettingsBottomSheetTest.privacySettingsAllEnabled.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.components.topbar.components.AboutAppDialogTest.aboutAppDialogVisible.png
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/di/HomeUiModule.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/components/privacySetting/PrivacySettingUiState.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/components/privacySetting/PrivacySettingsBottomSheet.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/components/privacySetting/PrivacySettingsEvent.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/components/privacySetting/PrivacySettingsViewModel.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/components/topbar/components/about/AboutAppDialog.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarEvent.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarUiState.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarViewModel.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileEvent.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileUiState.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileViewModel.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareEvent.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareUiState.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareViewModel.kt
  homeUi/src/main/res/drawable/ic_analytics_tracking.xml
  homeUi/src/main/res/drawable/ic_crashlytics.xml
  homeUi/src/main/res/values/strings.xml
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/components/privacySetting/PrivacySettingsBottomSheetTest.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/components/privacySetting/PrivacySettingsViewModelTest.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/components/topbar/components/AboutAppDialogTest.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/UserPrefsStorage.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/di/DatastoreModule.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/di/UserComponentModule.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/model/PrivacySettings.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/usecase/GetPrivacySettingsUseCase.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/usecase/UpdatePrivacySettingsUseCase.kt
Labels: enhancement

#118 Bind privacy settings and userInfo with the TracksTracker
  analytics/build.gradle.kts
  analytics/src/main/kotlin/com/gravatar/analytics/Tracker.kt
  analytics/src/main/kotlin/com/gravatar/analytics/TrackerSetupData.kt
  analytics/src/main/kotlin/com/gravatar/analytics/TrackerSetupDataProvider.kt
  analytics/src/main/kotlin/com/gravatar/analytics/tracks/TracksTracker.kt
  analytics/src/test/kotlin/com/gravatar/analytics/tracks/TrackTrackerTest.kt
  app/build.gradle.kts
  app/src/main/java/com/gravatar/app/AppTrackerSetupDataProvider.kt
  app/src/main/java/com/gravatar/app/analytics/AppEvent.kt
  app/src/main/java/com/gravatar/app/di/AppModule.kt
  app/src/test/kotlin/com/gravatar/app/AppTrackerSetupDataProviderTest.kt
  userComponent/schemas/com.gravatar.app.usercomponent.data.database.UserDatabase/3.json
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/database/UserDatabase.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/database/model/ProfileEntity.kt
Labels: enhancement
