Repository Automattic/Gravatar-Android, pull requests merged in 2025-07, with the labels that each got.

#29 Gravatar tab collapsed header
  homeUi/build.gradle.kts
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.GravatarScreenTest.gravatarScreen.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.components.GravatarHeaderTest.gravatarHeaderWithAvatar.png
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/HomeScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/components/GravatarHeader.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/header/ProfileHeader.kt
  homeUi/src/main/res/drawable/more_button.xml
  homeUi/src/main/res/values/strings.xml
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/components/GravatarHeaderTest.kt
Labels: enhancement

#31 Avatar selection queue
  config/detekt/detekt.yml
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarViewModel.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarViewModelTest.kt
Labels: enhancement

#34 Store user profile locally - persistent local storage
  build.gradle.kts
  gradle/libs.versions.toml
  userComponent/build.gradle.kts
  userComponent/schemas/com.gravatar.app.usercomponent.data.database.UserDatabase/1.json
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/RealProfileRepository.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/database/ProfileDao.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/database/UserDatabase.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/database/model/ProfileEntity.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/di/DatabaseModule.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/di/UserComponentModule.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/data/RealProfileRepositoryTest.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/data/database/ProfileDaoTest.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/di/DatabaseModuleTest.kt
Labels: enhancement

#38 Delete avatar
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarEvent.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarUiState.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarViewModel.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/components/AvatarDeletionConfirmationDialog.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/components/AvatarMoreOptionsPickerPopup.kt
  homeUi/src/main/res/drawable/check_circle.xml
  homeUi/src/main/res/drawable/delete_icon.xml
  homeUi/src/main/res/values/strings.xml
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarViewModelTest.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/RealUserRepository.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/repository/UserRepository.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/data/RealUserRepositoryTest.kt
Labels: enhancement

#36 UserSession persistence to keep and emit user logged in state
  app/src/main/java/com/gravatar/app/di/DispatcherModule.kt
  app/src/main/java/com/gravatar/app/navigation/RootNavigation.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/AuthTokenStorage.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/InMemoryUserSessionPersistence.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/RealAuthRepository.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/RealProfileRepository.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/RealUserRepository.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/di/UserComponentModule.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/model/UserSession.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/repository/AuthRepository.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/usecase/IsUserLoggedInUseCase.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/usecase/LoginUseCase.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/usecase/LogoutUseCase.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/data/FakeAuthTokenStorage.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/data/InMemoryUserSessionPersistenceTest.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/di/UserComponentModuleTest.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/domain/usecase/IsUserLoggedInUseCaseTest.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/domain/usecase/LoginUseCaseTest.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/domain/usecase/LogoutUseCaseTest.kt
Labels: enhancement

#40 Observe profile via Flow
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileEvent.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileUiState.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileViewModel.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileViewModelTest.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/RealProfileRepository.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/RealUserRepository.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/database/ProfileDao.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/repository/ProfileRepository.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/repository/UserRepository.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/usecase/GetAvatarUrlUseCase.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/data/RealProfileRepositoryTest.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/data/RealUserRepositoryTest.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/data/database/ProfileDaoTest.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/domain/usecase/GetAvatarUrlUseCaseTest.kt
Labels: enhancement

#44 Error state for avatar loading
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.components.ErrorViewWithRetryTest.errorViewWithRetry.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.GravatarScreenTest.gravatarScreenWithNullAvatars.png
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/components/ErrorViewWithRetry.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarEvent.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarUiState.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarViewModel.kt
  homeUi/src/main/res/values/strings.xml
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/components/ErrorViewWithRetryTest.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarScreenTest.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarViewModelTest.kt
Labels: enhancement

#45 Login Screen UI
  app/build.gradle.kts
  app/src/main/java/com/gravatar/app/MainActivity.kt
  app/src/main/java/com/gravatar/app/ui/theme/Color.kt
  app/src/main/java/com/gravatar/app/ui/theme/Theme.kt
  app/src/main/java/com/gravatar/app/ui/theme/Type.kt
  design/.gitignore
  design/build.gradle.kts
  design/src/main/kotlin/com/gravatar/app/design/theme/Color.kt
  design/src/main/kotlin/com/gravatar/app/design/theme/Theme.kt
  design/src/main/kotlin/com/gravatar/app/design/theme/Type.kt
  design/src/main/res/drawable/ic_gravatar.xml
  loginUi/build.gradle.kts
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreen.png
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreenDarkTheme.png
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreenLandscape.png
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreenLoading.png
  loginUi/src/main/kotlin/com/gravatar/app/loginUi/presentation/login/LoginScreen.kt
  loginUi/src/main/res/values/strings.xml
  loginUi/src/test/kotlin/com/gravatar/app/loginUi/presentation/login/LoginScreenTest.kt
  settings.gradle.kts
  testUtils/build.gradle.kts
Labels: enhancement

#46 Fix uploadAvatar when no avatar is selected
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarViewModel.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarViewModelTest.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/di/UserComponentModule.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/usecase/UploadUserAvatarUseCase.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/di/UserComponentModuleTest.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/domain/usecase/UploadAvatarUseCaseTest.kt
Labels: enhancement

#47 Add missing notification Snackbars
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/navigation/HomeNavigation.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarAction.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarViewModel.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileAction.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileViewModel.kt
  homeUi/src/main/res/values/strings.xml
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarViewModelTest.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileViewModelTest.kt
Labels: enhancement

#49 Empty state for avatars grid
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.GravatarScreenTest.gravatarScreenWithEmptyAvatars.png
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/components/AvatarsGridSection.kt
  homeUi/src/main/res/values/strings.xml
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarScreenTest.kt
Labels: enhancement

#51 Profile Screen UI update
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.profile.ProfileScreenTest.profileScreen.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.profile.about.AboutSectionTest.aboutSection_aboutSection_formEnabledFalse.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.profile.about.AboutSectionTest.aboutSection_mixSections_formEnabledFalse.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.profile.about.AboutSectionTest.aboutSection_nameSection_formEnabledFalse.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.profile.about.AboutSectionTest.aboutSection_professionalSection_formEnabledFalse.png
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileUiState.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileViewModel.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/about/AboutEditField.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/about/AboutEditSectionLabel.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/about/AboutEditorField.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/about/AboutFieldsSection.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/about/AboutInputField.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/about/AboutSection.kt
  homeUi/src/main/res/values/strings.xml
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileViewModelTest.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/profile/about/AboutSectionTest.kt
Labels: enhancement

#52 Handle unauthorized errors - 401
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/di/HomeUiModule.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/interceptors/HttpResponseCode.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/interceptors/UnauthorizeInterceptor.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/di/HttpClientModule.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/di/UserComponentModule.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/data/interceptors/UnauthorizeInterceptorTest.kt
  userComponent/src/test/kotlin/com/gravatar/app/usercomponent/di/UserComponentModuleTest.kt
Labels: enhancement

#60 Lock orientation to portrait
  app/src/main/AndroidManifest.xml
Labels: enhancement

#59 Update the styling of the selected avatar checkmark
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.GravatarScreenTest.gravatarScreen.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.components.SelectableAvatarTest.selectableAvatarSelected.png
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/components/SelectableAvatar.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/components/SelectableAvatarTest.kt
Labels: enhancement

#58 LoginScreen adjustments
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreen.png
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreenAuthorizationDenied.png
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreenDarkTheme.png
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreenLandscape.png
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreenLoading.png
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreenProfileLoadFailed.png
  loginUi/src/main/kotlin/com/gravatar/app/loginUi/presentation/login/LoginViewModel.kt
  loginUi/src/main/kotlin/com/gravatar/app/loginUi/presentation/login/components/LoginButton.kt
  loginUi/src/test/kotlin/com/gravatar/app/loginUi/presentation/login/LoginViewModelTest.kt
Labels: enhancement

#63 Theme colors
  design/src/main/kotlin/com/gravatar/app/design/theme/Color.kt
  design/src/main/kotlin/com/gravatar/app/design/theme/Theme.kt
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.GravatarScreenTest.gravatarScreen.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.GravatarScreenTest.gravatarScreenWithEmptyAvatars.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.GravatarScreenTest.gravatarScreenWithNullAvatars.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.components.NewAvatarButtonTest.newAvatarButton.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.components.SelectableAvatarTest.selectableAvatarLoading.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.components.SelectableAvatarTest.selectableAvatarSelected.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.profile.about.AboutSectionTest.aboutSection_aboutSection_formEnabledFalse.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.profile.about.AboutSectionTest.aboutSection_mixSections_formEnabledFalse.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.profile.about.AboutSectionTest.aboutSection_nameSection_formEnabledFalse.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.profile.about.AboutSectionTest.aboutSection_professionalSection_formEnabledFalse.png
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/HomeScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/components/AvatarsGridSection.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/components/NewAvatarButton.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/components/UploadAvatarSection.kt
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreen.png
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreenAuthorizationDenied.png
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreenDarkTheme.png
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreenLandscape.png
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreenLoading.png
  loginUi/screenshotTests/roborazzi/com.gravatar.app.loginUi.presentation.login.LoginScreenTest.loginScreenProfileLoadFailed.png
Labels: enhancement

#62 Add a banner when no avatar is selected
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.GravatarScreenTest.gravatarScreen.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.GravatarScreenTest.gravatarScreenWithAvatarsButNoneSelected.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.GravatarScreenTest.gravatarScreenWithEmptyAvatars.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.gravatar.GravatarScreenTest.gravatarScreenWithNullAvatars.png
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/components/AvatarsGridSection.kt
  homeUi/src/main/res/values/strings.xml
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarScreenTest.kt
Labels: enhancement

#66 Keep VMs alive for the main bottom tab destination
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/navigation/HomeNavigation.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileScreen.kt
Labels: bug

#70 Fix release build type
  build-logic/convention/src/main/kotlin/GravatarAndroidLibraryConventionPlugin.kt
Labels: enhancement

#68 No Internet banner on HomeScreen
  app/build.gradle.kts
  app/src/main/java/com/gravatar/app/di/AppModule.kt
  homeUi/build.gradle.kts
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.HomeScreenTest.homeScreenNoInternet.png
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/di/HomeUiModule.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/HomeScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/HomeUiState.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/HomeViewModel.kt
  homeUi/src/main/res/values/strings.xml
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/HomeScreenTest.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/HomeViewModelTest.kt
  networkMonitor/.gitignore
  networkMonitor/build.gradle.kts
  networkMonitor/src/main/AndroidManifest.xml
  networkMonitor/src/main/kotlin/com/gravatar/app/networkmonitor/AndroidNetworkMonitor.kt
  networkMonitor/src/main/kotlin/com/gravatar/app/networkmonitor/NetworkMonitor.kt
  networkMonitor/src/main/kotlin/com/gravatar/app/networkmonitor/di/NetworkMonitorModule.kt
  settings.gradle.kts
Labels: enhancement

#75 AboutAppDialog from the TopMenuPopup
  app/src/main/java/com/gravatar/app/di/AppModule.kt
  app/src/main/java/com/gravatar/app/di/BuildConfigModule.kt
  build-logic/convention/src/main/kotlin/GravatarAndroidApplicationConventionPlugin.kt
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.components.topbar.components.AboutAppDialogTest.aboutAppDialogVisible.png
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/AppVersion.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/components/topbar/TopBarPickerPopup.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/components/topbar/components/AboutAppDialog.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarEvent.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarUiState.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarViewModel.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/components/GravatarHeader.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileEvent.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileUiState.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileViewModel.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/profile/header/AnimatedProfileHeader.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareEvent.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareUiState.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareViewModel.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/components/ShareHeader.kt
  homeUi/src/main/res/drawable/top_bar_menu_about.xml
  homeUi/src/main/res/values/strings.xml
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/components/topbar/components/AboutAppDialogTest.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/GravatarViewModelTest.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/gravatar/components/GravatarHeaderTest.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/profile/ProfileViewModelTest.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareViewModelTest.kt
Labels: enhancement

#78 Update tab icons
  homeUi/src/main/res/drawable/gravatar.xml
  homeUi/src/main/res/drawable/profile_icon.xml
  homeUi/src/main/res/drawable/qr_code_icon.xml
Labels: enhancement

#79 Set keyboardType for email&phone input fields
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/components/ShareEditableField.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/components/SharePrivateContactInfo.kt
Labels: enhancement

#84 [Tooling] Add Debug / Release signing
  .configure
  .configure-files/gravatar-upload.jks.enc
  .configure-files/secrets.properties.enc
  build-logic/convention/src/main/kotlin/GravatarAndroidApplicationConventionPlugin.kt
  build.gradle.kts
  loginUi/build.gradle.kts
Labels: tooling

#77 Implement the public section in the Share tab
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.HomeScreenTest.homeScreen.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.HomeScreenTest.homeScreenNoInternet.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.profile.header.AnimatedProfileHeaderTest.animatedProfileHeader_whenSaving_showsCorrectLayout.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.profile.header.SaveProfileHeaderTest.profileHeader_savingState.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.share.components.SharePublicContactInfoTest.sharePublicContactInfoAllFields.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.share.components.SharePublicContactInfoTest.sharePublicContactInfoAllFieldsNonShared.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.share.components.SharePublicContactInfoTest.sharePublicContactInfoOnlyProfileUrl.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.share.components.SharePublicRowTest.sharePublicRowMultiLine.png
  homeUi/screenshotTests/roborazzi/com.gravatar.app.homeUi.presentation.home.share.components.SharePublicRowTest.sharePublicRowSingleLine.png
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareEvent.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareScreen.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareUiState.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareViewModel.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/components/ItemDivider.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/components/SharePublicContactInfo.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/components/SharePublicRow.kt
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/components/ShareSectionTitle.kt
  homeUi/src/main/res/values/strings.xml
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareViewModelTest.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/share/components/SharePublicContactInfoTest.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/share/components/SharePublicRowTest.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/model/UserSharePreferences.kt
Labels: enhancement

#82 Store private phone&email locally
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareViewModel.kt
  homeUi/src/test/kotlin/com/gravatar/app/homeUi/presentation/home/share/ShareViewModelTest.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/data/UserPrefsStorage.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/di/DatastoreModule.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/di/UserComponentModule.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/usecase/GetPrivateContactInfoUseCase.kt
  userComponent/src/main/kotlin/com/gravatar/app/usercomponent/domain/usecase/UpdatePrivateContactInfoUseCase.kt
Labels: enhancement

#88 Open TermsOfService and PrivacyPolicy in a customTab
  homeUi/build.gradle.kts
  homeUi/src/main/kotlin/com/gravatar/app/homeUi/presentation/home/components/topbar/components/AboutAppDialog.kt
Labels: enhancement
